name: ori
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip
  - aria2
  - git
  - pip:
        - torch==2.0.1
        - deepspeed==0.12.3
        - termcolor==2.3.0
        - biopython==1.79
        - ml-collections==0.1.1
        - numpy==1.21.2
        - modelcif==0.9
        - scipy
        - fvcore
        - wget
        - dm-tree
        - einops
        - sentencepiece
        - matplotlib